// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw84yu2K0qxSha4A8TQXDqYAJ-JZxpcLA',
    appId: '1:172613426022:web:e2abb5d054c05aad1706a7',
    messagingSenderId: '172613426022',
    projectId: 'crud-storage-11',
    authDomain: 'crud-storage-11.firebaseapp.com',
    storageBucket: 'crud-storage-11.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCcIkY44km2IvqkM6llNcoSrKv40t3XS4',
    appId: '1:172613426022:android:60c1d80f6550be381706a7',
    messagingSenderId: '172613426022',
    projectId: 'crud-storage-11',
    storageBucket: 'crud-storage-11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsyREDFOw6x_Ehd1haCk6GzY7WwZMphOM',
    appId: '1:172613426022:ios:cb6a2c377806f7cd1706a7',
    messagingSenderId: '172613426022',
    projectId: 'crud-storage-11',
    storageBucket: 'crud-storage-11.appspot.com',
    iosBundleId: 'com.sree.newfireproject.newfireproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsyREDFOw6x_Ehd1haCk6GzY7WwZMphOM',
    appId: '1:172613426022:ios:cb6a2c377806f7cd1706a7',
    messagingSenderId: '172613426022',
    projectId: 'crud-storage-11',
    storageBucket: 'crud-storage-11.appspot.com',
    iosBundleId: 'com.sree.newfireproject.newfireproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw84yu2K0qxSha4A8TQXDqYAJ-JZxpcLA',
    appId: '1:172613426022:web:16c9107d8e23e1ff1706a7',
    messagingSenderId: '172613426022',
    projectId: 'crud-storage-11',
    authDomain: 'crud-storage-11.firebaseapp.com',
    storageBucket: 'crud-storage-11.appspot.com',
  );
}
